<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-AL7G9RU" failures="0" tests="4" name="Seleniumbasics.TestNGDemo" time="5.020" errors="1" timestamp="2020-04-22T07:41:50 EDT" skipped="1">
  <testcase classname="Seleniumbasics.TestNGDemo" name="test1" time="0.008"/>
  <testcase classname="Seleniumbasics.TestNGDemo" name="test4" time="0.003"/>
  <testcase classname="Seleniumbasics.TestNGDemo" name="test3" time="0.000">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="Seleniumbasics.TestNGDemo" name="test2" time="5.009">
    <error message="Method Seleniumbasics.TestNGDemo.test2() didn&#039;t finish within the time-out 5000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method Seleniumbasics.TestNGDemo.test2() didn't finish within the time-out 5000
at java.base@13.0.2/java.util.concurrent.FutureTask.setException(FutureTask.java:249)
at java.base@13.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:269)
at java.base@13.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@13.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@13.0.2/java.lang.Thread.run(Thread.java:830)
]]>
    </error>
  </testcase> <!-- test2 -->
</testsuite> <!-- Seleniumbasics.TestNGDemo -->
